vpc-name      = "Jenkins-vpc"
igw-name      = "Jenkins-igw"
subnet-name   = "Jenkins-subnet"
rt-name       = "Jenkins-route-table"
sg-name       = "Jenkins-Server SG"
instance-name = "Jenkins-Server"
key-name      = "Suraj-Sanjay"
iam-role      = "Jenkins-iam-role"